### ISSUE TITLE
chinachu-wuiのURLにIPv6アドレスが使えない

### ISSUE THREAD

**Issue by eru** [Harekaze/pvr.chinachu#11]
`http://[...]:10772` の様なIPv6アドレスを含むURLを指定すると、実際にはサーバサイドへリクエストが飛ばないようです。
（Kodiの問題のような気もします。）

また、DNSの正引きの結果、AAAAレコード（=IPv6アドレス）が返ってくるような場合でも、同様の状態になるようです。

chinachu自体はAPIについては、IPv6でアクセスしてもレスポンスは返すことは確認済みです。

**Comment by mzyy94** [comment]
v6での接続を想定していなかったのでこのような問題が起きるとは全然知りませんでした。
Kodi側の仕様の確認とpvr.chinachuの挙動の確認を要するので修正までには時間がかりそうですが、次のメジャーバージョンアップまでには修正できればしていく形で進めていきたいと思います。
ご報告ありがとうございます。

**Comment by viddypiddy** [comment]
Sorry for English: IPv6 only WUI works for me.

Details:
I am using IPv6 only (AAAA record without A record) for the Chinachu WUI (latest gamma), with Kodi 17.4-RC1 (20170804-b6bf39c) on Windows and everything works.

**Comment by mzyy94** [comment]
Hey viddypiddy,
Thank you for your report. That's great news. :)
I'm going to try to check compatibility with IPv6 only network even now.
Therefore I need more report, so let this issue be opened

**Comment by viddypiddy** [comment]
That's great. I think IPv6 compatibility is very important, and avoids hassle with NAT on IPv4 👍

**Comment by mzyy94** [comment]
Hey everyone.
I tested IPv6 access with Kodi 18.0 Leia alpha1, and it works fine.
`http://[::1]:20772` works very well :)
