### ISSUE TITLE
TV項目が表示されない

### ISSUE THREAD

**Issue by mizucoffee** [Harekaze/pvr.chinachu#14]
## 概要
Harekaze導入後、認識するもTV項目が表示されない。

## 情報
Kodi：16.1
Harekaze：3.2.0

## 状況
TV：有効
PVR：認識
<img width="1680" alt="screen shot 2016-11-13 at 23 39 31" src="https://cloud.githubusercontent.com/assets/9247699/20246457/751d2e3a-a9fa-11e6-8f40-a977382c75fc.png">

明示的なエラー：無し
一通りの設定済（IPとか）

明らかにサーバーを認識してない気がするんですけど設定はあってるんです...

**Comment by mzyy94** [comment]
https://github.com/Harekaze/pvr.chinachu/wiki/Configuration
ここに記載のある通りの値が入力されて設定ができているかどうか一度確認してみてください。

**Comment by mizucoffee** [comment]
すみません、解決しました。

http://のつけ忘れでした...
fullにそんな意味があるとは...

ご迷惑おかけしました。ありがとうございます。

**Comment by mzyy94** [comment]
いえいえ、解決できたようで何よりです。
プロトコル指定がない場合に警告を出すよう改善します。
