### ISSUE TITLE
Chinachu γで動作しない

### ISSUE THREAD

**Issue by nidixx** [Harekaze/pvr.chinachu#15]
Kodi 16.1・Chinachu Beta・Harekaze 3.2.0 にて正常に動作していましたが
Chinachu γ にアップデートして数時間後、TV項目が表示されなくなりました。

エラーログ：
ERROR: PVR - exception '"type mismatch! call is<type>() before get<type>()" && is<std::string>()' caught while trying to call 'GetChannels' on add-on 'Chinachu:'.

Issues #7 と似たログですが、Chinachu γからの変更点に"ジャンル増加"とあったので類似の問題でしょうか。

**Comment by mzyy94** [comment]
エラーログより、チャンネル構造体部分のJSONパースが失敗しているようですね。
おそらく、おっしゃる通りChinachu γからの仕様変更による影響で動作しなくなっているようです。
年明けに調査し、修正版としてあげますので、今しばらくお待ちください。

**Comment by mzyy94** [comment]
v3.3.0 でChinachu γの仕様変更に追従しました。

**Comment by mzyy94** [comment]
Kodi 16.1 for macOSとKodi 16.1 on OSMCにて、
[v3.3.0](https://github.com/Harekaze/pvr.chinachu/releases/tag/v3.3.0) と https://github.com/Chinachu/Chinachu/commit/829ed89578e8597a0373f11e78921b732754f52e との組み合わせでエラーなく動作することを確認。
