### ISSUE TITLE
Android ARM Build Error

### ISSUE THREAD

**Issue by mizucoffee** [Harekaze/pvr.chinachu#16]
### Description

```
./bootstrap
./configure --host=arm-linux-androideabi
make CPPFLAGS=-DPICOJSON_USE_LOCALE=0 # この行で失敗
ls pvr.chinachu.*.zip
```
を実行したときに失敗する

#### エラー
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libpvrchinachu.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

### Your Environment
Android NDK導入、及びパス通し済み（ndk-buildコマンド実行可）。

#### Hardware
- MacBook Pro Early 2015

#### Software
- OS X El Capitan 10.11.6 (15G1212)

### Versions
- Harekaze for Kodi: 3.3.0

Git Tag:a6b6ae5

### P.S.
Releaseページにて3.2.0からAndroid版のビルド済みファイルのDLが不可になっていますが、もしかしてこちらと関係ありますでしょうか。

**Comment by mzyy94** [comment]
Fixed fb4170f315f1cea2bbba51e80d79330f4fbe5ebb

**Comment by mizucoffee** [comment]
Thanks! ;D
