### ISSUE TITLE
番組表の録画予約表示がおかしい

### ISSUE THREAD

**Issue by ibulog** [Harekaze/pvr.chinachu#17]
Kodi 17 Windows devel-betaにて、番組表の録画予約表示に異常があります。

具体的には、予約していない番組の一部、場合によっては全部に予約済みマークがつきます。

2017/01/15あたりのcommitで異常が発生した気がします。

**Comment by mzyy94** [comment]
ご報告ありがとうございます。
いろいろといじくり回していたら予約関連のメモリを破壊してしまったようで、macOSやAndroid TVでも再現することを確認しています。
修正していきますので、不具合が生じていることが確認できているコミットハッシュの連絡をお願いします。

**Comment by ibulog** [comment]
ご返信ありがとうございます。

cbea7df519f155a88211777d19b4b77288fc3a8bが原因のcommitだと思われます。

**Comment by mzyy94** [comment]
調査してみます。
そのコミットは実際にビルドして動かしているものですか？
そうでない場合は、ビルドして動かしているコミットハッシュも教えてください。

**Comment by ibulog** [comment]
現在は33498391dd7d48a7792f61969408125caba5dd50をVS2015でビルドし使用しています。
このバージョンでは、番組表の不具合は出ておりません。

**Comment by mzyy94** [comment]
問題の発生している部分を修正しました。
本件は32bit環境でのlong型のサイズを考慮していなかったため、36進数文字列の数値変換が範囲外としてエラーとなっていました。
デバッグ環境として用意していた手元のmacOS/Linux/Android/iOSは全て64bitなため、ご指摘いただかなかったら気づいていませんでした。
ご報告ありがとうございます。
最新コミットで修正されたと思うので、動作確認をお願いします。

**Comment by ibulog** [comment]
先ほど最新版を使用してみましたが、問題は発生しませんでした。
修正していただきありがとうございます。

**Comment by mzyy94** [comment]
😄
