### ISSUE TITLE
Chinachu γ の環境で、Transcodeがされない

### ISSUE THREAD

**Issue by skwsk** [Harekaze/pvr.chinachu#19]
Kodi 16.1 + pvr.chinachu 3.3.0 にて、あまり太くない無線環境(実行速度10Mbps程度)にて、
Transcode を使い、ライブ視聴していまして、とても快適に使わせていただいています。
ただ、このたび Chinachu側の環境を Chinachu γ + Mirakurun 2.2.0 にアップデートしたところ、
画像がきれいになりましたが、カクカクと頻繁に止まりまして、どうも Transcode がされなくなったようです。
Chinachuをβに戻す(Mirakurunも削除)と、今まで通り視聴可能です。
Transcode のオプションは、Chinachu γ との組み合わせではサポートされていないのでしょうか。
ChinachuのWebUIからライブ視聴することは、Chinachu γ でも、問題なく視聴可能です。
クライアント(Kodi 16.1 + pvr.chinachu 3.3.0)は違うPCでも試してみましたが、結果は同じでした。
サーバ(Chinachu)は、一台しかないので、その設定の間違いという可能性も捨てきれないのですが、
サーバ側には特別な設定はいらなかったように記憶しています。

**Comment by mzyy94** [comment]
ご報告ありがとうございます。
挙動の確認と修正を、月末あたり登場予定の4.1に盛り込んでおきます。
暫しお待ちください :bow:

**Comment by mzyy94** [comment]
おっとバージョンを見落としていました。
3.3.0はサポート外となりますので4.0へあげて視聴を試してみてください。

**Comment by skwsk** [comment]
連絡ありがとうございます。3.3.0は、もうサポート外なんですね。了解しました。
4.0ということは、Kodiも17.xである必要があるんですよね。
メインで使っているPCでは、まだKodiを17.xにあげられないので、サブのPCで試してみます。
