### ISSUE TITLE
chinachuを同じパソコンに入れてスタンドアローンで動作させる場合のURL

### ISSUE THREAD

**Issue by kimityan555** [Harekaze/pvr.chinachu#20]
初歩的な質問で申し訳ありません。

Raspberry Pi 3にOSMC、Mirakurun、Chinachu yをインストールして、Harekazeでライブ視聴をと思ったのですが、今のところURLの設定のところに「http://localhost:10772」として動いているのですが、ハードディスクレコーダーとしてしか動作させるつもりがないので、オフラインで動作させたいのですが、本体にIPアドレスがないとライブ視聴&録画予約ができないことに気づきました。

chinachuの設定ではMirakurunのパスに「http+unix://%2Fvar%2Frun%2Fmirakurun.sock/」と指定されていて、オフラインでも動作するのですが、Harekazeの場合はどうすればいいかがわかりません。
IPアドレスがないと無理ですか？

**Comment by mzyy94** [comment]
Chinachuは何らかのネットワークアドレスで待ち受けているはずなので、そのアドレスを指定していただくと利用できるかと思います。
逆を返すと、Chinachuはネットワークアドレスが割り振られない環境では正常に動作しないので、Chinachuが動作しているということは、なにかしら待ち受けているネットワークが必ず存在しています。
MirakurunはUNIXソケットで待ち受けることが可能ですが、Chinachu自体はそういう挙動をしないと認識しております。
オフラインという意味では、127.0.0.1のIPv4アドレスが割り振られたlo0やloインターフェースがOSMCにあるはずなので、そちらを指定して試してみてはいかがでしょう。
