### ISSUE TITLE
チャンネルの並び順

### ISSUE THREAD

**Issue by fugetutada** [Harekaze/pvr.chinachu#22]
[バックエンドのチャンネル序列を使用]をONにするとGR/BS/CSが入り交じったチャンネル順になりますが、これをChinachuと同じ並び順にしていただけないでしょうか。
OFFにして手動で並べ替えれば良いのですが、数が多くKodiのUIも相まってかなり困難です。

よろしくお願いします。

**Comment by mzyy94** [comment]
Kodi 18 alpha1でChannel numberが正しく順番通りになる挙動を確認したので次のv5.0.0までお待ちください。
https://github.com/Harekaze/pvr.chinachu/commit/9b6682675f55eb7816726cc6467870b6f499a030#diff-434985a08b9e76029bc30212ceeaf11fR58
