### ISSUE TITLE
android arm64対応について

### ISSUE THREAD

**Issue by qx0901** [Harekaze/pvr.chinachu#23]
RootedなAndroid arm６４上のkodiにHarekazeをインストールして使用を試みたところ、ライブラリをロードできないエラーが生じております。arm64のAndroidには対応していないのでしょうか？

libpvr.chinachu.soのコピー先はWikiでは”$ANDROID_DATA/app/org.xbmc.kodi-1/lib/arm/”となっておりますが、こちらの環境ではこのディレクトリはありませんでしたので、”/data/app/org.xbmc.kodi-2/lib/arm64/”にファイルを配置しました。PermissionやOwnerの変更はWikiに従っています。この環境でKodiを起動したところ、Harekazeは立ち上がっていないようです。

kodi.logに以下が出力されております。
ERROR: Unable to load /data/app/org.xbmc.kodi-2/lib/arm64/libpvr.chinachu.so, reason: dlopen failed: "/data/app/org.xbmc.kodi-2/lib/arm64/libpvr. chinachu.so" is 32-bit instead of 64-bit

HarekazeはArm64 Androidのkodi上では使用できないのでしょうか?

**Comment by mzyy94** [comment]
こちらのデバッグ環境ではnon-rootな64ビットのAndroid TVで動作しているので、エラーの通りバイナリの確認をして再度適切なバイナリを配置いただく必要がありそうです。

**Comment by qx0901** [comment]
早速の回答有り難うございます。

zipファイル
pvr.chinachu.4.0.0-multiarch.zip
からkodiにインストールしたのですが、64bitのlibpvr.chinachu.soファイルも上記zipに含まれているのでしょうか?
それとも、自分でソースからビルドする必要があるのでしょうか？

**Comment by mzyy94** [comment]
Releaseに記載の通り、multiarchパッケージには以下のバイナリが含まれています。

> Since v4.0.0, distributing binary package is targeted multi architecture.
> 
> - macOS
> - Windows
> - Linux [64bit]
> - Raspberry Pi [armv7]
> - Android [armv7]
> - iOS (beta)

残念ならがAndroid版はarmv7しか含まれておらず、現状は各々ビルドしていただく形となっております。
今後のリリースで配布する可能性もありますが、今はソースコードからビルドいただくようお願いいたします。

**Comment by qx0901** [comment]
回答頂きまして、ありがとうございました。
明確になりましたのですっきりいたしました。

ビルドに挑戦いたします。
