### ISSUE TITLE
Support for Kodi 18.0

### ISSUE THREAD

**Issue by viddypiddy** [Harekaze/pvr.chinachu#24]
I noticed that Kodi 18.0 is not a supported target at this point, but still I tried to build it from source and bumped the version numbers to load the addon.

It did not load, sadly. Is this because support for Kodi 18.0 is not finished, or is it my mistake?

Tested on: 
```
Kodi (18.0-ALPHA1 Git:20170805-nogitfound). Platform: Linux x86 64-bit
```

Outcome:
```
WARNING: Unable to resolve: /pvr.chinachu.so ADDON_GetTypeVersion, reason: /home/media/.kodi/addons/pvr.chinachu/pvr.chinachu.so: undefined symbol: ADDON_GetTypeVersion
ERROR: Unable to resolve exports from dll /home/media/.kodi/addons/pvr.chinachu/pvr.chinachu.so
ERROR: UpdateAddons - failed to create add-on Harekaze (Chinachu PVR client), status = 5
```

**Comment by viddypiddy** [comment]
Here are the import dependencies i changed:

To:
```
                <import addon="kodi.binary.instance.pvr" version="5.5.0"/>
                <import addon="kodi.binary.instance.videocodec" version="1.0.1"/>
```

From:
```
                <import addon="xbmc.pvr" version="5.2.1"/>
                <import addon="xbmc.codec" version="1.0.1"/>
```

**Comment by viddypiddy** [comment]
I just did some research on this, and found that there is quite alot of API changes for Binary addons for Kodi 18.0. So it is to be expected that it does not load successfully.

Thank you for the great addon, I will wait for a working version for Kodi 18.0.

**Comment by mzyy94** [comment]
Great trying :)
Kodi 18 will be released with 64-bit support for windows and more improvements (api change including).
In order to follow this/these change(s), maybe I need more time to make this add-on completely.
So please wait until beta or release candidate version of kodi 18 becomes available.
