### ISSUE TITLE
Can't install pvr.chinachu 2.0.0 to Kodi 16.0 on OSX.

### ISSUE THREAD

**Issue by eru** [Harekaze/pvr.chinachu#5]
### Environment
- OSX El Capitan 10.11.3
- Kodi (kodi-16.0-Jarvis-x86_64.dmg)
  - Build: 16.0 Git:2016-02-20-a5f3a00
  - Compile: Feb 20 2016
- pvr.chinachu v2.0.0
### Error messages
- Faild to install Add-on from zip file
  - The dependency on kodi.guilib version 5.10.0 could no...
  - screenshots: [1](https://gyazo.com/948acbcd2ec1c9ad6f0950d604d7ea6f), [2](https://gyazo.com/1d10d76607527a51e56bee60147bc9e8)

**Comment by mzyy94** [comment]
Thank you for the report.
I'll check it in 12 hours.
Please wait a moment.. ;)

**Comment by mzyy94** [comment]
Solved this issue in commit 1824ca9.
And fixed version 2.0.1 will be released.
