### ISSUE TITLE
API version error on Kodi 16.0 (Linux)

### ISSUE THREAD

**Issue by benmoran56** [Harekaze/pvr.chinachu#6]
I updated to Kodi 16.0 today on my Arch Linux install. Unfortunately, the Chinachu addon would not start. I tried to build the latest version, and also tried the latest release. I get this message in the kodi.log file: 

ERROR:  PVR - Add-on 'Chinachu PVR client' is using an incompatible API version. XBMC minimum API version = '4.1.0', add-on API version '1.9.6'

Thanks!

**Comment by benmoran56** [comment]
Nevermind!  The issue was caused by old kodi userdata.  I manually deleted the old data, and it started working as expected.

**Comment by mzyy94** [comment]
Thank you for the reporting :)
