### ISSUE TITLE
プラグインが動作しない

### ISSUE THREAD

**Issue by tosono** [Harekaze/pvr.chinachu#7]
KODI 16.1で以下のメッセージがログに記録され、プラグインが動作しません。
ERROR: PVR - exception '"type mismatch! call is<type>() before get<type>()" && isstd::string()' caught while trying to call 'PVR::CPVRClient::GetChannels' on add-on 'Chinachu:'. Please contact the developer of this add-on: mzyy94

なんとなくの原因は分かっていて、Mirakurun利用のため、chinachuをdevel-betaに上げているからと思います。
schedule.jsonの内容が、何かしら変わってしまって影響を受けているだろう事までは、予想出来ますが、
デバッグ環境が無いので、何処でエラーになってるかまでは、分かりません。

schdule.jsonを添付しますので、出来ましたらご対応頂けると、助かります。
[schdule.zip](https://github.com/mzyy94/pvr.chinachu/files/300544/schdule.zip)

**Comment by mzyy94** [comment]
状況把握しました。
Mirakurun対応を今週末あたりに開始するので、少々お待ちいただければと思います。

**Comment by mzyy94** [comment]
本件の原因を調査したところ、CS番組のカテゴリ名が存在していなかったため、あたいの取得に失敗していたということがわかりました。
その点修正した2.0.2を公開したので、動作確認いただければとおもいます。
